### ISSUE TITLE
个别网站会乱码

### ISSUE THREAD

**Issue by TonyJason** [linpinger/foxbook-android#1]
大神好,昨天闲着无聊,研究了一下大神的项目,有几个不明白的地方：
1：为什么搜索里面偏偏没有百度呢?内置的搜索除了必应,其他的都很鸡肋.
2：测试了一下，大部分的网站基本上都能解析出章节目录以及章节内容,但是有的非常慢还有的会出现乱码;
3：发现有的书添加到首页之后也更新了本书,但是第二次进去这书就没了。
4：发现经常莫名其妙的崩溃，出现程序已停止等错误,我太渣了,很多代码都看不懂，也不知道问题出在哪里？
5：更新书本的时候，查看章节列表，不能实时的更新listview  的显示问题，而且我觉得这个缓存应该用service来处理更好.
以上问题纯属我无聊提交的issue。只是我个人的看法，也许大神有自己的考量!

**Comment by linpinger** [comment]
多谢研究，其实我不是专业的程序员，这些小程序纯粹是个人爱好，所以都以满足自己的需求为先，所以会有很多不人性化的地方，因为它都偏向于自己的操作方式
1. 没有百度，是因为百度的搜索结果里面得不到网址，都已经转码了，包括其他的搜索引擎，不是转码了地址，就是用的https，自己技术不好，处理不了这些，所以就没有添加进去
2. 搜索引擎得出来的结果，有些不一定是目录页的地址，有些是书的介绍页地址，所以有些得不出目录，有些网站的目录顺序也会有问题，这是由于该网站使用了css等东西，生成的目录顺序用浏览器正常，程序分析后顺序就会坑了，还有的网站内容不是直接生成在网页中，用了ajax技术，这样的目前处理不了，慢是因为一些小站点的速度就不快，所以下载页面自然也慢
3. 这个问题我没遇到，没有例子不好分析，如果有碰到，下次可以麻烦你将链接发过来分析一下崩溃的原因
4. 代码多了我也头晕，崩溃的原因是由于写的不规范，习惯了C的方式，把习惯都带到java里面了，另外异常都是简单的输出到标准错误输出，甚至没有处理，所以崩溃很正常，不过自己用的时候倒没出现崩溃情况，有也调试一下就搞定了，^_^
5. 更新的时候，我就呆在那里不动，等它更新完毕，所以你懂得，另外我不会用service啊，之前都没用过，android的那些api都从网上找来的，很多都不太熟练

另，由于一直想搞个大新闻，最近也在重写这个项目，不准备使用sqlite3当储存结构了，内部使用自定义结构来处理数据，储存准备用不标准的xml来搞定，这样不用忍受android那蛋疼的sqlite3接口，2016-12-25号的时候基本搞定了，然后就是调试了，bug量比以前多多了，痛并快乐着

**Comment by TonyJason** [comment]
感谢回复,看了我都汗颜了，不是程序猿也这么厉害!只能膜拜
另外后来测试了一下百度,发现确实不行,很多网页都被百度转码了,要么就跳转到了目标网页的手机版,确实有不少问题!还有那个章节列表是不是匹配li标签呢,我测试只要是li标签的基本上都能识别出来，但是我发现有的网站用的是table表格来做列表，这样子好像识别不出来。比如这个网站http://www.shuotxts.com/8/19/19491/index.html
还有搜索那一块我觉得要是能写一套通用的匹配小说网站的搜索页面的规则就好了，我发现这些网站用的都是百度站内搜索http://zhannei.baidu.com/cse/search?s=920895234054625192&ie=UTF-8&q=关键词，规则应该都是通用的。现在越来越的小说APP面临收费，我也只是想找一个自己能看书的方式，然后就搜索到了你这个项目，大神有兴趣可以加我QQ2995834094一起讨论研究呗。
